# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 12:50


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='path',
            field=models.CharField(default='/tmp/polaroid', max_length=1024),
            preserve_default=False,
        ),
    ]
