# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 13:09


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_gallery_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.CharField(db_index=True, max_length=14, primary_key=True, serialize=False, unique=True)),
                ('path', models.ImageField(upload_to=b'')),
                ('thumb', models.CharField(max_length=1024)),
                ('caption', models.CharField(blank=True, default='', max_length=1024, null=True)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('gallery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Gallery')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
