# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='thumb',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
