# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-22 18:42


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20160325_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='large',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
